# Generated by Django 3.1.5 on 2021-01-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210121_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='personal_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring', to='quickstart.professor'),
        ),
    ]
