# Generated by Django 3.1.5 on 2021-01-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20210121_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='personal_tutor',
        ),
        migrations.AddField(
            model_name='student',
            name='personal_tutor',
            field=models.ManyToManyField(related_name='tutoring', to='quickstart.Professor'),
        ),
    ]
