# Generated by Django 3.1.5 on 2021-01-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20210121_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='personal_tutor',
        ),
        migrations.AddField(
            model_name='student',
            name='personal_tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tutoring', to='quickstart.professor'),
            preserve_default=False,
        ),
    ]
